importando a Biblioteca Numpy (Trabalhando com Arrays)

In [79]:
import numpy as np

criando uma matriz unidimensional

In [80]:
mt = np.array([12,23,45,67,78])
print (mt)

[12 23 45 67 78]


In [81]:
#Criar array de um tipos especifico
#array do tipo float
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

#array do tipo int
mtint = np.array([1,2,3,4], dtype = np.int32)
print (mtint , type(mtint))




[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3 4] <class 'numpy.ndarray'>


In [82]:
#mudar o tipo do array 
mtint = np.array([12.65,23.43,45.55,67.66,78.32])

#usando a função(.astype(tipo do dado que deseja))
mtint_new = mtint.astype(np.int32)
print (mtint_new)

[12 23 45 67 78]


In [83]:
#criar uma matriz bidimensional
mt_bi = ([1,2,3],[4,5,6],[7,8,9])
print(mt_bi)

([1, 2, 3], [4, 5, 6], [7, 8, 9])


In [84]:
#criar arrays vazias tipificadas
# np.empty([tamanho da matriz], dtype = tipo do dados)
mt2 = np.empty([3,2], dtype = int)
print(mt2)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


In [85]:
# criar  matriz com valores zeros
# np.zeros([tamanho da matriz])
mt3 = np.zeros([3,3])
print(mt3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [86]:
# criar matris com valores igual a 1 
#np.ones([Tamanho da matriz])

mt4 = np.ones([3,2])
print(mt4)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [87]:
# criar matriz com diagonal principal igual a 1 e os demais numeros igual a zero
#np.eye(n = tamanho da matriz (deve ser matriz quadratica n x n))
mt5 = np.eye(2)
print(mt5)

[[1. 0.]
 [0. 1.]]


[ np.random ] sempre cria valores entre zero e um positivo e um negativo

In [88]:
# criando arrays com valores aleatorios entre zero e um
mt6 = np.random.random((6))
print(mt6)

[0.98880295 0.46898047 0.6020406  0.44433452 0.95412468 0.81204761]


In [89]:
# criando valores aleatorios normal(Real)
mt7 = np.random.randn((5))
print(mt7)

[-1.17928119  1.67338156 -0.62135547 -1.55835039  0.87165723]


In [90]:
# criando matriz com valores aleatorios 
mt8 = (10*np.random.random((3,4)))
print(mt8)

[[3.46445603 8.33918506 6.36661061 2.97568769]
 [3.81439538 2.53008585 6.95800224 5.56835603]
 [8.87053112 3.84702141 9.25703618 0.73294751]]


In [91]:
# outra forma de criar valores aleatorios
gnr = np.random.default_rng(1)
mt9 = gnr.random(3)
print(mt9)
print (gnr)

[0.51182162 0.9504637  0.14415961]
Generator(PCG64)


In [92]:
#gerar array de inteiros

mt10 = gnr.integers(10, size=(3,4))
print(mt10)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [93]:
# np.unique(array_nome) remove repetições
mt11 = np.array([1,1,2,3,4,4,5,56,7,8,8,9,20])
mt11 = np.unique(mt11)
print(mt11)

[ 1  2  3  4  5  7  8  9 20 56]


In [94]:
# função para matrizes
mt_bi =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mt_bi)
# acessar elemento da matriz/ Nome_matriz[linha][coluna]
print(mt_bi[0][2])
# saber o tamanaho da matriz/ Nome_matriz.shape
print(mt_bi.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
(3, 3)


In [95]:
#funções matematicas
#mostra o maior valor da matriz
print(mt_bi.max())
#mostra o menor valor da matriz
print(mt_bi.min())
#mostra a soma dos valores da matriz
print(mt_bi.sum())
#mostra o valor da media dos valores da matriz
print(mt_bi.mean())
#mostra o valor do desvio padrão dos valores da matriz
print(mt_bi.std())

9
1
45
5.0
2.581988897471611


In [96]:
#funções universais aplicadas a todos os elemnentos da matriz
#calcula a raiz quadrada de cada elemento
mt12 = np.array([1,4,9,16,25,36])
print(np.sqrt(mt12))
#mostra o valor exponencial de cada eleemnto
print(np.exp(mt12))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [97]:
#extração de elemento
#Nome_array[valor incial: valor final] percorre a alista do elemento inicial até o final
#ignora o ultimo valor
print(mt12[0:2])
print(mt12[2:5])
print(mt12[:5])
print(mt12[3:])

[1 4]
[ 9 16 25]
[ 1  4  9 16 25]
[16 25 36]


In [98]:
#extração de elemento matriz
#Nome_matriz[linhaInicial:linhaFinal,ColunaInicial:ColunaFinal]
print(mt_bi[:2,:2])

[[1 2]
 [4 5]]


In [99]:
#adição e multiplicação de matrizes
mt_bi =np.array([[1,2,3],[4,5,6],[7,8,9]])
mt_bi_2 =np.array([[20,3,6],[1,3,7],[5,1,9]])

rest_Soma = mt_bi + mt_bi_2 
print(rest_Soma)
rest_Multi = mt_bi*mt_bi_2
print(rest_Multi)


[[21  5  9]
 [ 5  8 13]
 [12  9 18]]
[[20  6 18]
 [ 4 15 42]
 [35  8 81]]


In [107]:
#transposição de matrizes
mt_bi_3 =np.array([[20,3,6],[1,3,7]])
print(mt_bi_3)
print("\n")
mt_bi_3_t = mt_bi_3.T
print(mt_bi_3_t)

#outra forma de fazer a transposição
mt_bi_3_t = mt_bi_3.transpose((1,0))
print(F"\n{mt_bi_3_t}")

[[20  3  6]
 [ 1  3  7]]


[[20  1]
 [ 3  3]
 [ 6  7]]

[[20  1]
 [ 3  3]
 [ 6  7]]


In [108]:
#expressão lógicas 
#criando matrizes com nuemros aleatorios
v = np.random.randn(4,4)
print(v)
#se os numeros for maior que zero ficam true , se não fica false
x = (v>0)
print(x)
# testa a matriz x , se a condição for corresponde fica 1 , se não fica -1
#np.where(condição, true (faz isso) ,false(faz isso))
z = np.where(x>0,1,-1)
print(z)

[[-0.75793849  0.55972762 -0.09286556  0.20470806]
 [-0.97415463 -1.63173564  0.58827678 -0.33448568]
 [ 1.98834527  0.52018408 -0.52558817 -1.29290666]
 [ 1.08818113 -2.4240668   0.51652235  1.31846644]]
[[False  True False  True]
 [False False  True False]
 [ True  True False False]
 [ True False  True  True]]
[[-1  1 -1  1]
 [-1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1  1  1]]
